# Generated by Django 3.2 on 2021-04-22 21:31

from django.db import migrations, models
import main_atelier.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_atelier', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('photo', models.ImageField(upload_to=main_atelier.models.Events.get_file_name_events)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
            ],
        ),
    ]
